export const roadmapMap: Record<string, string> = {
  python: "AI/ML -> Python Programming",
  "machine learning": "AI/ML -> Machine Learning Foundations",
  "deep learning": "AI/ML -> Deep Learning Core Concepts",
  tensorflow: "AI/ML -> Deep Learning Module",
  pytorch: "AI/ML -> Deep Learning with PyTorch",
  "scikit-learn": "AI/ML -> Classical ML with scikit-learn",
  "natural language processing": "AI/ML -> NLP Fundamentals",
  "computer vision": "AI/ML -> Computer Vision Fundamentals",
  react: "Web Dev -> React Essentials",
  "next.js": "Web Dev -> Next.js Full Stack",
  javascript: "Web Dev -> JavaScript Fundamentals",
  typescript: "Web Dev -> TypeScript for Web Apps",
  node: "Web Dev -> Backend with Node.js",
  express: "Web Dev -> API Development with Express",
  html: "Web Dev -> HTML Foundations",
  css: "Web Dev -> CSS Layout and Responsive Design",
  cybersecurity: "Cybersecurity -> Security Fundamentals",
  "network security": "Cybersecurity -> Network Security Basics",
  "penetration testing": "Cybersecurity -> Penetration Testing Intro",
  "ethical hacking": "Cybersecurity -> Ethical Hacking Practices",
  cryptography: "Cybersecurity -> Applied Cryptography",
  siem: "Cybersecurity -> SIEM and Monitoring",
  docker: "DevOps -> Docker Fundamentals",
  kubernetes: "DevOps -> Kubernetes Orchestration",
  aws: "Cloud -> AWS Basics",
  azure: "Cloud -> Azure Fundamentals",
  "ci/cd": "DevOps -> CI/CD Pipelines",
  terraform: "DevOps -> Infrastructure as Code",
  linux: "DevOps -> Linux for Engineers",
  sql: "Data Science -> SQL for Data Analysis",
  mongodb: "Data Engineering -> NoSQL with MongoDB",
  pandas: "Data Science -> Data Analysis with pandas",
  numpy: "Data Science -> Numerical Computing with NumPy",
  "data visualization": "Data Science -> Data Visualization Essentials",
  statistics: "Data Science -> Statistics for Analytics",
  git: "Software Engineering -> Version Control with Git"
};
